services:

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - "redis-data-volume:/data"

  app-1:
    build:
      context: .
      dockerfile: Dockerfile-app
    depends_on:
      - "redis"
    ports:
      - "3000:3000"
    volumes:
      - "./:/usr/src/app"
    command: npm run start:dev

  app-2:
    build:
      context: .
      dockerfile: Dockerfile-app
    depends_on:
      - "redis"
    ports:
      - "3001:3000"
    volumes:
      - "./:/usr/src/app"
    command: npm run start:dev

  app-3:
    build:
      context: .
      dockerfile: Dockerfile-app
    depends_on:
      - "redis"
    ports:
      - "3002:3000"
    volumes:
      - "./:/usr/src/app"
    command: npm run start:dev

  app-4:
    build:
      context: .
      dockerfile: Dockerfile-app
    depends_on:
      - "redis"
    ports:
      - "3003:3000"
    volumes:
      - "./:/usr/src/app"
    command: npm run start:dev

volumes:
  redis-data-volume: